"""e257: does the massive neuron's provenance migrate across positions? M = the block-2 candidate with the largest
median |coefficient| (the massive-activation neuron where one exists), N = a matched normal candidate. For each
sequence the neuron is ablated ONLY at the position where it is most active; footprints at L are measured at every
position. Reported: the share of footprint energy at the source position vs the rest of the sequence, the number of
receiver positions carrying at least 10% of the source footprint's norm, and whether receiver footprints identify the
ablated neuron (nearest natural centroid among the K candidates; cosine with the neuron's natural centroid), against
the source position's own footprint."""
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from func_common import *
tag = sys.argv[1]; c = Cache(tag); L = mid(c); model, tok, fam = load_model(c.name); arch = Arch(model, fam); NS = 16; ids_seq = c.s["eval_ids"][:NS].to(DEV); NT = NS * CTX; b = 2; D = c.D; lab = c.d["lab"]; A = c.d["A"]; R = A[(lab["type"] == T_MLP) & (lab["block"] == b)].float().to(DEV)
led, tn, tc = dominant(model, arch, c, ids_seq, b); run = make_runner_logits(model, arch, c, ids_seq, [L], NT, b); S0 = run(); typ = typical_mask(S0[L]); big = tc.abs() >= tc.abs().quantile(0.5); idx, lab_i, keep = classes(tn, typ & big, 20); K = len(keep); S1 = run(tn); Cn = unit(centroids((S0[L] - S1[L])[idx], lab_i, K)); med = torch.stack([tc[idx][lab_i == k].median().abs() for k in range(K)]); M = med.argmax(); N = (med - med.median()).abs().argmin(); out = {}
for nm, j in (("massive", M), ("normal", N)):
    act = led[:, keep[j]].abs().reshape(NS, CTX); p_star = act.argmax(1); src = p_star + torch.arange(NS, device=DEV) * CTX; S2 = run(torch.full((NT,), int(keep[j]), device=DEV), ablate_positions=src); F = (S0[L] - S2[L]).reshape(NS, CTX, D); Fn = F.norm(dim=2)
    src_norm = Fn[torch.arange(NS, device=DEV), p_star]; mask = torch.ones(NS, CTX, dtype=torch.bool, device=DEV); mask[torch.arange(NS, device=DEV), p_star] = False; other = Fn[mask].reshape(NS, CTX - 1)
    energy_share_source = ((src_norm ** 2) / (src_norm ** 2 + (other ** 2).sum(1)).clamp_min(1e-9)).median().item(); n_receivers = ((other > 0.1 * src_norm[:, None]).sum(1).float()).median().item()
    rec_pos = (Fn > 0.1 * src_norm[:, None]) & mask; Fr = unit(F[rec_pos]); Fs = unit(F[torch.arange(NS, device=DEV), p_star])
    out[nm] = dict(neuron=int(keep[j]), median_coef=med[j].item(), source_position_median=p_star.float().median().item(), energy_share_source=energy_share_source, receivers_per_sequence=n_receivers, receiver_identifies_neuron=((Fr @ Cn.T).argmax(1) == j).float().mean().item() if len(Fr) else float("nan"), receiver_cos_with_centroid=(Fr @ Cn[j][:, None])[:, 0].median().item() if len(Fr) else float("nan"), source_identifies_neuron=((Fs @ Cn.T).argmax(1) == j).float().mean().item(), source_cos_with_centroid=(Fs @ Cn[j][:, None])[:, 0].median().item(), chance=1.0 / K)
    log(f"{tag} {nm} neuron {int(keep[j])} (|coef| {med[j]:.1f}, ablated only at its top position, median position {out[nm]['source_position_median']:.0f}): footprint energy at the source position {energy_share_source:.2f}, receivers with >10% of the source norm per sequence {n_receivers:.0f} | receiver footprints identify the neuron {out[nm]['receiver_identifies_neuron']:.2f} (cos with its centroid {out[nm]['receiver_cos_with_centroid']:.2f}); the source position's own footprint {out[nm]['source_identifies_neuron']:.2f} (cos {out[nm]['source_cos_with_centroid']:.2f}); chance {1 / K:.2f}")
record(f"e257_receiver_{tag}", dict(model=tag, b=b, L=L, K=K, **{k: v for k, v in out.items()}), " | ".join(f"{nm} (|coef| {v['median_coef']:.1f}): source energy share {v['energy_share_source']:.2f}, receivers/seq {v['receivers_per_sequence']:.0f}, receivers identify it {v['receiver_identifies_neuron']:.2f} vs source {v['source_identifies_neuron']:.2f} (chance {v['chance']:.2f})" for nm, v in out.items()))
