"""e299: propagation as a field. (G) The token x layer x feature tensor of the candidates' natural ablation over all
levels after the write: energy of the top layer-modes and feature-modes, against the same tensor for random
directions injected at the same tokens. (F) The empirical impulse response: a single write injected at one token
per sequence, and the response energy at each later level by token offset, for the write itself, a core vector, a
leftover vector and a random vector; the fraction of the response at other tokens per level and its decay."""
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from desc_common import *
tag = sys.argv[1]; c = Cache(tag); L = mid(c); model, tok, fam = load_model(c.name); arch = Arch(model, fam); NS = 12; ids_seq = c.s["eval_ids"][:NS].to(DEV); NT = NS * CTX; NB = c.NB; b = 2; D = c.D; lab = c.d["lab"]; A = c.d["A"]; R = A[(lab["type"] == T_MLP) & (lab["block"] == b)].float().to(DEV); levels = list(range(b + 1, NB)); run = make_runner(model, arch, c, ids_seq, levels, NT)
led, tn, tc = dominant(model, arch, c, ids_seq, b); S0 = run(); typ = typical_mask(S0[L]); big = tc.abs() >= tc.abs().quantile(0.5); S1 = run(b, tn); idx, lab_i, keep = classes(tn, typ & big, 20); K = len(keep)
T3 = torch.stack([(S0[lv] - S1[lv]) for lv in levels]); torch.manual_seed(0); Vr = unit(torch.randn(NT, D, device=DEV)); inj = torch.zeros(NT, D, device=DEV); inj[typ] = tc.abs()[typ][:, None] * Vr[typ]; S2 = run(inject=inj, inject_block=b + 1); T3r = torch.stack([(S2[lv] - S0[lv]) for lv in levels])
def modes(T):
    Xf = torch.nan_to_num(T.reshape(-1, D)); Xf = Xf - Xf.mean(0, keepdim=True); ef = torch.linalg.eigvalsh((Xf.T @ Xf).double()).flip(0).clamp_min(0); ef = (ef / ef.sum()).float(); Xl = torch.nan_to_num(T.reshape(len(levels), -1)); el = torch.linalg.eigvalsh((Xl @ Xl.T).double()).flip(0).clamp_min(0); el = (el / el.sum()).float(); return dict(feature_top1=ef[0].item(), feature_top8=ef[:8].sum().item(), feature_top32=ef[:32].sum().item(), feature_prank=(1 / (ef ** 2).sum()).item(), layer_top1=el[0].item(), layer_top2=el[:2].sum().item(), layer_prank=(1 / (el ** 2).sum()).item())
mw, mr = modes(T3), modes(T3r)
F = (S0[L] - S1[L])[idx]; Fc = F - F.mean(0, keepdim=True); U32 = torch.linalg.svd(Fc, full_matrices=False)[2][:32]; k0 = int(torch.bincount(lab_i, minlength=K).argmax()); cen = F[lab_i == k0].mean(0); zvec = unit((cen @ U32.T) @ U32); qvec = unit(cen - (cen @ U32.T) @ U32); wvec = unit(R[keep[k0]]); amp = tc[idx][lab_i == k0].abs().median(); p0 = CTX // 2; tokens = torch.arange(NS, device=DEV) * CTX + p0; offsets = list(range(0, 33)); imp = {}
for nm, v in (("write", wvec), ("core", zvec), ("leftover", qvec), ("random", unit(torch.randn(D, device=DEV)))):
    inj = torch.zeros(NT, D, device=DEV); inj[tokens] = amp * v[None]; S2 = run(inject=inj, inject_block=b + 1); rec = {}
    for lv in (b + 1, b + 3, L, NB - 2):
        Rr = (S2[lv] - S0[lv]).reshape(NS, CTX, D); e = (Rr[:, p0: p0 + 33] ** 2).sum(2).mean(0); e_before = (Rr[:, :p0] ** 2).sum(2).mean(0).mean(); rec[lv] = dict(other_fraction=(e[1:].sum() / e.sum()).item(), offset1=(e[1] / e[0]).item(), offset8=(e[8] / e[0]).item(), offset32=(e[32] / e[0]).item(), before_source=(e_before / e[0]).item())
    imp[nm] = rec
log(f"{tag} (K {K}): (G) tensor modes, WDD vs random: feature top-1 {mw['feature_top1']:.2f}/{mr['feature_top1']:.2f}, top-8 {mw['feature_top8']:.2f}/{mr['feature_top8']:.2f}, top-32 {mw['feature_top32']:.2f}/{mr['feature_top32']:.2f}, feature participation rank {mw['feature_prank']:.1f}/{mr['feature_prank']:.1f}; layer top-1 {mw['layer_top1']:.2f}/{mr['layer_top1']:.2f}, top-2 {mw['layer_top2']:.2f}/{mr['layer_top2']:.2f}, layer participation rank {mw['layer_prank']:.1f}/{mr['layer_prank']:.1f} | (F) impulse at one token, fraction of response at other tokens (offset-1 / offset-8 / offset-32 relative to the source) by level: " + " || ".join(f"{nm}: " + ", ".join(f"lv{lv} {v['other_fraction']:.2f} ({v['offset1']:.2f}/{v['offset8']:.2f}/{v['offset32']:.2f}, before {v['before_source']:.3f})" for lv, v in rec.items()) for nm, rec in imp.items()))
record(f"e299_propagation_{tag}", dict(model=tag, b=b, L=L, K=K, modes_wdd=mw, modes_random=mr, impulse={nm: {str(k): v for k, v in rec.items()} for nm, rec in imp.items()}), f"modes WDD/random feature top-8 {mw['feature_top8']:.2f}/{mr['feature_top8']:.2f} prank {mw['feature_prank']:.1f}/{mr['feature_prank']:.1f}, layer top-2 {mw['layer_top2']:.2f}/{mr['layer_top2']:.2f} | impulse other-token fraction at L: " + " ".join(f"{nm} {rec[L]['other_fraction']:.2f}" for nm, rec in imp.items()))
