"""e300: the geometry of causal states across hundreds of neurons. All block-2 neurons with at least five dominant
tokens: centroid descendants at L, core coordinates z (projection onto the 16-dim function basis of the >=20-token
candidates) and write directions. Reported: pairwise |cosine| of cores, descendants, writes and random vectors;
participation ranks; the correlation across pairs between write cosine and core cosine (is the core a property of the
write?); core cosine for the most write-similar decile against the rest."""
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from func_common import *
tag = sys.argv[1]; c = Cache(tag); L = mid(c); model, tok, fam = load_model(c.name); arch = Arch(model, fam); NS = 16; ids_seq = c.s["eval_ids"][:NS].to(DEV); NT = NS * CTX; b = 2; D = c.D; lab = c.d["lab"]; A = c.d["A"]; R = A[(lab["type"] == T_MLP) & (lab["block"] == b)].float().to(DEV)
led, tn, tc = dominant(model, arch, c, ids_seq, b); run = make_runner_logits(model, arch, c, ids_seq, [L], NT, b); S0 = run(); typ = typical_mask(S0[L]); big = tc.abs() >= tc.abs().quantile(0.5); idx, lab_i, keep = classes(tn, typ & big, 20); K = len(keep); idx5, lab5, keep5 = classes(tn, typ & big, 5); N = len(keep5)
S0i = run(positions=idx); S1i = run(tn, positions=idx); dl = S0i["lg"] - S1i["lg"]; dl = dl - dl.mean(1, keepdim=True); F = (S0i[L] - S1i[L])[idx]; Fc = F - F.mean(0, keepdim=True); G = dl @ dl.T; evg, Vg = torch.linalg.eigh(G); Zt = Vg.flip(1)[:, :256] * evg.flip(0)[:256].clamp_min(0).sqrt()[None]; Zt = Zt - Zt.mean(0, keepdim=True); U_fn = torch.linalg.svd(Fc.T @ Zt, full_matrices=False)[0][:, :16]
S1a = run(tn); Fall = (S0[L] - S1a[L]); Cd = torch.stack([Fall[idx5][lab5 == k].mean(0) for k in range(N)]); Cdc = Cd - Cd.mean(0, keepdim=True); Zc = Cdc @ U_fn; Wn = unit(R[keep5]); torch.manual_seed(0); Rn = unit(torch.randn(N, D, device=DEV)); iu = torch.triu_indices(N, N, 1, device=DEV)
pc = lambda X: (unit(X) @ unit(X).T)[iu[0], iu[1]]; cz, cd, cw, cr = pc(Zc), pc(Cdc), pc(Wn), pc(Rn)
def prank(X):
    ev = torch.linalg.eigvalsh(X.T @ X / len(X)).clamp_min(0); return (ev.sum() ** 2 / (ev ** 2).sum()).item()
def spearman(a_, b_):
    ra = a_.argsort().argsort().float(); rb = b_.argsort().argsort().float(); return torch.corrcoef(torch.stack([ra, rb]))[0, 1].item()
top = cw >= cw.quantile(0.9); res = dict(N=N, abs_cos_core=cz.abs().median().item(), abs_cos_descendant=cd.abs().median().item(), abs_cos_write=cw.abs().median().item(), abs_cos_random=cr.abs().median().item(), prank_core=prank(Zc), prank_descendant=prank(Cdc), prank_write=prank(Wn - Wn.mean(0, keepdim=True)), spearman_write_vs_core=spearman(cw, cz), spearman_write_vs_descendant=spearman(cw, cd), spearman_descendant_vs_core=spearman(cd, cz), core_cos_top_write_decile=cz[top].median().item(), core_cos_rest=cz[~top].median().item())
log(f"{tag} ({N} neurons with >= 5 tokens): median |cos| core {res['abs_cos_core']:.2f}, descendant {res['abs_cos_descendant']:.2f}, write {res['abs_cos_write']:.2f}, random {res['abs_cos_random']:.2f} | participation rank core {res['prank_core']:.1f} (of 16), descendant {res['prank_descendant']:.1f}, write {res['prank_write']:.1f} (of {D}) | Spearman write-cos vs core-cos {res['spearman_write_vs_core']:+.2f}, write vs descendant {res['spearman_write_vs_descendant']:+.2f}, descendant vs core {res['spearman_descendant_vs_core']:+.2f} | core cos for the top write-similar decile {res['core_cos_top_write_decile']:+.2f} vs rest {res['core_cos_rest']:+.2f}")
record(f"e300_crossneuron_{tag}", dict(model=tag, b=b, L=L, K=K, **res), f"N {N}: |cos| core {res['abs_cos_core']:.2f} desc {res['abs_cos_descendant']:.2f} write {res['abs_cos_write']:.2f} random {res['abs_cos_random']:.2f}; prank core {res['prank_core']:.1f} desc {res['prank_descendant']:.1f} write {res['prank_write']:.1f}; Spearman w-core {res['spearman_write_vs_core']:+.2f} w-desc {res['spearman_write_vs_descendant']:+.2f} desc-core {res['spearman_descendant_vs_core']:+.2f}; top-decile core cos {res['core_cos_top_write_decile']:+.2f} vs {res['core_cos_rest']:+.2f}")
