"""e309: why is the perturbation cloud low-rank, and is it curved? The natural descendant cloud at L (candidates,
per token) compared with the ordinary residual covariance at L, the attention-output and MLP-output covariances at
block L (typical tokens), the block-2 write rows, and random matched vectors: participation ranks, and the energy of
the descendant top-16 and of the function core inside each covariance's top-16 and top-64 (chance 16/D, 64/D).
Curvature: the local participation rank of 50-nearest-neighbour patches of the cloud against its global rank."""
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from func_common import *
tag = sys.argv[1]; c = Cache(tag); L = mid(c); model, tok, fam = load_model(c.name); arch = Arch(model, fam); NS = 16; ids_seq = c.s["eval_ids"][:NS].to(DEV); NT = NS * CTX; b = 2; D = c.D; lab = c.d["lab"]; A = c.d["A"]; R = A[(lab["type"] == T_MLP) & (lab["block"] == b)].float().to(DEV)
led, tn, tc = dominant(model, arch, c, ids_seq, b); run = make_runner_logits(model, arch, c, ids_seq, [L], NT, b); comp = {}
hs = [arch.attn_lin(L).register_forward_hook(lambda m, i, o: comp.__setitem__("attn", o.detach().float().reshape(-1, D))), arch.mlp_lin(L).register_forward_hook(lambda m, i, o: comp.__setitem__("mlp", o.detach().float().reshape(-1, D)))]; S0 = run(); [h.remove() for h in hs]
typ = typical_mask(S0[L]); big = tc.abs() >= tc.abs().quantile(0.5); idx, lab_i, keep = classes(tn, typ & big, 20); K = len(keep); S0i = run(positions=idx); S1i = run(tn, positions=idx); dl = S0i["lg"] - S1i["lg"]; dl = dl - dl.mean(1, keepdim=True); F = (S0i[L] - S1i[L])[idx]; Fc = F - F.mean(0, keepdim=True); G = dl @ dl.T; evg, Vg = torch.linalg.eigh(G); Zt = Vg.flip(1)[:, :256] * evg.flip(0)[:256].clamp_min(0).sqrt()[None]; Zt = Zt - Zt.mean(0, keepdim=True); S_fn = torch.linalg.svd(Fc.T @ Zt, full_matrices=False)[0][:, :16]; S_desc = torch.linalg.svd(Fc, full_matrices=False)[2][:64].T
torch.manual_seed(0); clouds = {"descendants": Fc, "residual_state": S0[L][typ] - S0[L][typ].mean(0, keepdim=True), "attention_output": comp["attn"][typ] - comp["attn"][typ].mean(0, keepdim=True), "mlp_output": comp["mlp"][typ] - comp["mlp"][typ].mean(0, keepdim=True), "block2_writes": R - R.mean(0, keepdim=True), "random": torch.randn(len(idx), D, device=DEV)}
def prank(X):
    ev = torch.linalg.eigvalsh(X.T @ X / len(X)).clamp_min(0); return (ev.sum() ** 2 / (ev ** 2).sum()).item()
inside = lambda A_, B_: ((B_.T @ A_) ** 2).sum().item() / A_.shape[1]; out = {}
for nm, X in clouds.items():
    U = torch.linalg.svd(X, full_matrices=False)[2]; out[nm] = dict(prank=prank(X), core_in_top16=inside(S_fn, U[:16].T), core_in_top64=inside(S_fn, U[:64].T), desc16_in_top16=inside(S_desc[:, :16], U[:16].T), desc16_in_top64=inside(S_desc[:, :16], U[:64].T))
nn = torch.cdist(Fc, Fc).topk(51, dim=1, largest=False).indices[:, 1:]; torch.manual_seed(1); samp = torch.randperm(len(idx), device=DEV)[:64]; local = torch.tensor([prank(Fc[nn[i]] - Fc[nn[i]].mean(0, keepdim=True)) for i in samp.tolist()]); curv = dict(local_prank_median=local.median().item(), global_prank=prank(Fc), ratio=(local.median() / prank(Fc)).item())
log(f"{tag} (K {K}, D {D}; chance 16/D {16 / D:.3f}, 64/D {64 / D:.3f}): participation ranks: " + ", ".join(f"{nm} {v['prank']:.1f}" for nm, v in out.items()) + " | function core inside each cloud's top-16 / top-64: " + ", ".join(f"{nm} {v['core_in_top16']:.2f}/{v['core_in_top64']:.2f}" for nm, v in out.items()) + " | descendant top-16 inside each cloud's top-16 / top-64: " + ", ".join(f"{nm} {v['desc16_in_top16']:.2f}/{v['desc16_in_top64']:.2f}" for nm, v in out.items()) + f" | curvature: local rank (50-NN patches) {curv['local_prank_median']:.1f} vs global {curv['global_prank']:.1f} (ratio {curv['ratio']:.2f})")
record(f"e309_cloudorigin_{tag}", dict(model=tag, b=b, L=L, K=K, clouds=out, curvature=curv), "pranks " + " ".join(f"{nm} {v['prank']:.1f}" for nm, v in out.items()) + " | core in top16/64: " + " ".join(f"{nm} {v['core_in_top16']:.2f}/{v['core_in_top64']:.2f}" for nm, v in out.items()) + f" | local/global rank {curv['local_prank_median']:.1f}/{curv['global_prank']:.1f}")
