"""e315: intervention on the coordinate with predictions made once, from natural data, and no refitting. For each of
eight core directions u_k (PLS pairing), +delta u_k and -delta u_k are injected at foreign tokens at the natural
footprint norm. Measured: the logit change, the future core coordinate two blocks later, the KL, the entropy change,
and the state change at the following token. Predicted without refitting: the logit change from the ridge map W
fitted on natural descendants, and the future core coordinate from the transport map A fitted on natural descendants
in the fixed core basis (e293). Reported: median cosine actual vs predicted for logits and for the future core, the
odd/even structure of the scalar observables (entropy odd, KL even), and cross-token reach against random directions."""
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from func_common import *
tag = sys.argv[1]; c = Cache(tag); L = mid(c); model, tok, fam = load_model(c.name); arch = Arch(model, fam); NS = 12; ids_seq = c.s["eval_ids"][:NS].to(DEV); NT = NS * CTX; NB = c.NB; b = 2; D = c.D; lf = L + 2 if L + 2 < NB - 1 else NB - 2; nk = 8
led, tn, tc = dominant(model, arch, c, ids_seq, b); run = make_runner_logits(model, arch, c, ids_seq, [L, lf], NT, b); S0 = run(); typ = typical_mask(S0[L]); big = tc.abs() >= tc.abs().quantile(0.5); idx, lab_i, keep = classes(tn, typ & big, 20); K = len(keep)
S0i = run(positions=idx); S1i = run(tn, positions=idx); dl = S0i["lg"] - S1i["lg"]; dl = dl - dl.mean(1, keepdim=True); F = (S0i[L] - S1i[L])[idx]; Fc = F - F.mean(0, keepdim=True); Ff = (S0i[lf] - S1i[lf])[idx]; Ffc = Ff - Ff.mean(0, keepdim=True); fnorm = F.norm(dim=1).median()
Ud, Sd, Vd = torch.linalg.svd(dl, full_matrices=False); Zs = Ud[:, :256] * Sd[:256][None]; B = Vd[:256].T; Zs = Zs - Zs.mean(0, keepdim=True); Up, Sp, Wt = torch.linalg.svd(Fc.T @ Zs, full_matrices=False); P = Up[:, :16]; u = Up[:, :nk].T
Gx = Fc.T @ Fc; W = torch.linalg.solve(Gx + 1e-1 * Gx.diagonal().mean() * torch.eye(D, device=DEV), Fc.T @ Zs); zL, zf = Fc @ P, Ffc @ P; Amap = torch.linalg.lstsq(zL, zf).solution
foreign = torch.nonzero(typ & ~torch.isin(tn, keep))[:, 0]; foreign = foreign[(foreign % CTX) < CTX - 1][:1024]; base = run(positions=foreign); lg0 = base["lg"]; lp0 = torch.log_softmax(lg0, -1); torch.manual_seed(0); rnd = unit(torch.randn(nk, D, device=DEV))
def probe(v):
    inj = torch.zeros(NT, D, device=DEV); inj[foreign] = fnorm * v[None]; r = run(positions=foreign, inject=inj, inject_block=L + 1); dlr = r["lg"] - lg0; dlr = dlr - dlr.mean(1, keepdim=True); lp1 = torch.log_softmax(r["lg"], -1); kl = (lp0.exp() * (lp0 - lp1)).sum(1); ent = (-(lp1.exp() * lp1).sum(1)) - (-(lp0.exp() * lp0).sum(1)); dz = ((r[lf] - S0[lf])[foreign]) @ P; nxt = (r[lf] - S0[lf])[foreign + 1].norm(dim=1) / (r[lf] - S0[lf])[foreign].norm(dim=1).clamp_min(1e-9); return dict(dl=dlr, kl=kl.median().item(), ent=ent.median().item(), dz=dz, cross=nxt.median().item())
out = {}
for k in range(nk):
    pp, pm = probe(u[k]), probe(-u[k]); pred_l = ((fnorm * u[k][None]) @ W) @ B.T; pred_z = fnorm * Amap[k][None]
    out[k] = dict(logit_cos_plus=((unit(pp["dl"]) * unit(pred_l)).sum(1)).median().item(), logit_cos_minus=((unit(pm["dl"]) * unit(-pred_l)).sum(1)).median().item(), future_core_cos_plus=((unit(pp["dz"]) * unit(pred_z)).sum(1)).median().item(), future_core_cos_minus=((unit(pm["dz"]) * unit(-pred_z)).sum(1)).median().item(), kl_plus=pp["kl"], kl_minus=pm["kl"], entropy_plus=pp["ent"], entropy_minus=pm["ent"], cross_plus=pp["cross"])
rr = [probe(rnd[k]) for k in range(nk)]; rand_cross = sum(x["cross"] for x in rr) / nk; rand_kl = sum(x["kl"] for x in rr) / nk
lc = torch.tensor([[v["logit_cos_plus"], v["logit_cos_minus"]] for v in out.values()]); fc = torch.tensor([[v["future_core_cos_plus"], v["future_core_cos_minus"]] for v in out.values()]); ent_odd = sum(1 for v in out.values() if v["entropy_plus"] * v["entropy_minus"] < 0) / nk; kl_even = sum(1 for v in out.values() if v["kl_plus"] > 0 and v["kl_minus"] > 0) / nk; kl_ratio = sum(v["kl_plus"] for v in out.values()) / nk / max(rand_kl, 1e-9)
res = dict(logit_cos_median=lc.median().item(), logit_cos_min=lc.min().item(), future_core_cos_median=fc.median().item(), future_core_cos_min=fc.min().item(), entropy_sign_flips=ent_odd, kl_positive_both=kl_even, kl_vs_random=kl_ratio, cross_token=sum(v["cross_plus"] for v in out.values()) / nk, cross_token_random=rand_cross)
log(f"{tag} (K {K}): no-refit predictions for interventions along 8 core directions (+ and -): logit change cos to the ridge prediction median {res['logit_cos_median']:.2f} (min {res['logit_cos_min']:.2f}); future core coordinate cos to the transport-map prediction median {res['future_core_cos_median']:.2f} (min {res['future_core_cos_min']:.2f}); entropy change flips sign with the direction in {res['entropy_sign_flips']:.2f} of coordinates (odd), KL positive for both signs in {res['kl_positive_both']:.2f} (even), KL {res['kl_vs_random']:.2f}x random directions; cross-token reach {res['cross_token']:.2f} vs random {res['cross_token_random']:.2f}")
record(f"e315_multiobs_{tag}", dict(model=tag, b=b, L=L, K=K, per_direction={str(k): v for k, v in out.items()}, **res), f"logit cos {res['logit_cos_median']:.2f} (min {res['logit_cos_min']:.2f}) | future core cos {res['future_core_cos_median']:.2f} (min {res['future_core_cos_min']:.2f}) | entropy odd {res['entropy_sign_flips']:.2f} KL even {res['kl_positive_both']:.2f} KL/random {res['kl_vs_random']:.2f} | cross {res['cross_token']:.2f} vs {res['cross_token_random']:.2f}")
