"""e322: the quotient at birth. At level b+1 the descendant is the write itself, so the birth quotient is a subspace of
write space; its transport (through the data-free operator and through the actual descendants) is compared with the
mid-level quotient: overlap, and the logit footprint decoded from the birth quotient applied to birth descendants,
from the transported birth quotient applied to mid descendants, and from the mid quotient itself."""
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from quot_common import *
tag = sys.argv[1]; S0_ = Setup(tag, levels=[0]); L = S0_.L; b = 2; S = Setup(tag, levels=[b + 1, b + 2, L]); d = 16; nat = S.natural(); tr, te = S.halves(len(S.idx)); Z, _ = logit_scores(nat["dl"], tr); dln = unit(nat["dl"])
Fb = nat["F"][b + 1]; Fbc = Fb - Fb[tr].mean(0, keepdim=True); Pb = pls(Fbc[tr], Z[tr], d); FL = nat["F"][L]; FLc = FL - FL[tr].mean(0, keepdim=True); PL = pls(FLc[tr], Z[tr], d); T = S.fit_T(b + 1, L, seed=5); Pt = torch.linalg.qr(T.T @ Pb)[0]
res = dict(K=S.K, chance=d / S.D, birth_vs_mid_overlap=inside(Pb, PL), transported_birth_vs_mid_overlap=inside(Pt, PL), logit_from_birth_quotient_at_birth=knn_cos(Fbc @ Pb, dln, tr, te), logit_from_transported_birth_quotient_at_mid=knn_cos(FLc @ Pt, dln, tr, te), logit_from_birth_quotient_applied_at_mid=knn_cos(FLc @ Pb, dln, tr, te), logit_from_mid_quotient=knn_cos(FLc @ PL, dln, tr, te), birth_quotient_in_write_span=inside(Pb, torch.linalg.qr(S.W2[S.keep].T)[0]))
log(f"{tag} (K {S.K}, chance {d / S.D:.3f}): birth quotient vs mid quotient overlap {res['birth_vs_mid_overlap']:.2f}, transported birth quotient vs mid {res['transported_birth_vs_mid_overlap']:.2f}; logit decoded from the birth quotient at birth {res['logit_from_birth_quotient_at_birth']:.2f}, from the transported birth quotient at mid {res['logit_from_transported_birth_quotient_at_mid']:.2f}, from the birth quotient applied unchanged at mid {res['logit_from_birth_quotient_applied_at_mid']:.2f}, from the mid quotient {res['logit_from_mid_quotient']:.2f}; birth quotient inside the span of the candidate writes {res['birth_quotient_in_write_span']:.2f}")
record(f"e322_birth_{tag}", dict(model=tag, L=L, **res), f"birth-mid overlap {res['birth_vs_mid_overlap']:.2f} transported {res['transported_birth_vs_mid_overlap']:.2f}; logit from birth {res['logit_from_birth_quotient_at_birth']:.2f} transported-at-mid {res['logit_from_transported_birth_quotient_at_mid']:.2f} birth-at-mid {res['logit_from_birth_quotient_applied_at_mid']:.2f} mid {res['logit_from_mid_quotient']:.2f}; in write span {res['birth_quotient_in_write_span']:.2f}")
