"""e337: the homomorphism F(a + b) ~ F(a) + F(b) quantified globally: 40 random pairs drawn across families (WDD
atoms, random directions, attention writes, cov-matched), each pair injected singly and jointly at the natural
amplitude; the distribution of the relative error and cosine at the logits and in the core coordinate, split by
family combination and by the cosine between the two members' effects (aligned, orthogonal, opposed)."""
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from quot_common import *
tag = sys.argv[1]; S = Setup(tag, levels=[0]); L = S.L; S = Setup(tag, levels=[L]); d = 16; nat = S.natural(); F = nat["F"][L]; tr, te = S.halves(len(S.idx)); Fc = F - F[tr].mean(0, keepdim=True); Z, Bv = logit_scores(nat["dl"], tr); P = pls(Fc[tr], Z[tr], d); lab = S.c.d["lab"]; A = S.c.d["A"]
torch.manual_seed(0); Ratt = A[(lab["type"] == T_ATT) & (lab["block"] <= S.b)].float().to(DEV); Sc = S.S0[L][S.typ] - S.S0[L][S.typ].mean(0, keepdim=True); fams = {"wdd": S.W2[torch.randperm(S.DFF, device=DEV)[:20]], "random": unit(torch.randn(20, S.D, device=DEV)), "attention": unit(Ratt[torch.randperm(len(Ratt), device=DEV)[:20]]), "cov": unit((torch.randn(20, len(Sc), device=DEV) / len(Sc) ** 0.5) @ Sc)}; names = list(fams); sub = S.pool[::2][:1024]
def eff(v): r = S.inject_family(v[None], S.b + 1, positions=sub, seed=3); return r["dl"] @ Bv, r["F"][L] @ P
rows = []
for t in range(40):
    fa, fb = names[t % 4], names[(t // 4) % 4]; i, j = int(torch.randint(0, 20, (1,))), int(torch.randint(0, 20, (1,))); a, b_ = fams[fa][i], fams[fb][j]
    Ea, za = eff(a); Eb, zb = eff(b_); Eab, zab = eff(a + b_); lin = Ea + Eb; zl = za + zb; ca = ((unit(Ea) * unit(Eb)).sum(1)).median().item()
    rows.append(dict(fams=f"{fa}+{fb}", effect_cos=ca, logit_cos=((unit(Eab) * unit(lin)).sum(1)).median().item(), logit_err=((Eab - lin).norm(dim=1) / Eab.norm(dim=1).clamp_min(1e-9)).median().item(), core_cos=((unit(zab) * unit(zl)).sum(1)).median().item(), core_err=((zab - zl).norm(dim=1) / zab.norm(dim=1).clamp_min(1e-9)).median().item()))
T_ = torch.tensor([[r["effect_cos"], r["logit_cos"], r["logit_err"], r["core_cos"], r["core_err"]] for r in rows]); al = T_[:, 0] > 0.3; op = T_[:, 0] < -0.3; ort = ~al & ~op; same = torch.tensor([r["fams"].split("+")[0] == r["fams"].split("+")[1] for r in rows])
def med(m, col): return T_[m, col].median().item() if m.any() else float("nan")
res = dict(n=len(rows), logit_cos_all=T_[:, 1].median().item(), logit_err_all=T_[:, 2].median().item(), core_cos_all=T_[:, 3].median().item(), core_err_all=T_[:, 4].median().item(), logit_err_aligned=med(al, 2), logit_err_orthogonal=med(ort, 2), logit_err_opposed=med(op, 2), core_err_aligned=med(al, 4), core_err_orthogonal=med(ort, 4), core_err_opposed=med(op, 4), logit_err_same_family=med(same, 2), logit_err_cross_family=med(~same, 2), worst_logit_err=T_[:, 2].max().item(), worst_core_err=T_[:, 4].max().item(), n_aligned=int(al.sum()), n_opposed=int(op.sum()))
log(f"{tag} (40 cross-family pairs): F(a+b) vs F(a)+F(b) at the logits cos {res['logit_cos_all']:.2f} relative error {res['logit_err_all']:.2f} (worst {res['worst_logit_err']:.2f}); in the core cos {res['core_cos_all']:.2f} error {res['core_err_all']:.2f} (worst {res['worst_core_err']:.2f}); logit error for aligned / orthogonal / opposed effects {res['logit_err_aligned']:.2f} / {res['logit_err_orthogonal']:.2f} / {res['logit_err_opposed']:.2f} (n {res['n_aligned']}/{40 - res['n_aligned'] - res['n_opposed']}/{res['n_opposed']}); same-family {res['logit_err_same_family']:.2f} vs cross-family {res['logit_err_cross_family']:.2f}")
record(f"e337_homomorphism_{tag}", dict(model=tag, L=L, **res, rows=rows), f"logit cos {res['logit_cos_all']:.2f} err {res['logit_err_all']:.2f} (worst {res['worst_logit_err']:.2f}); core cos {res['core_cos_all']:.2f} err {res['core_err_all']:.2f}; aligned/orth/opposed {res['logit_err_aligned']:.2f}/{res['logit_err_orthogonal']:.2f}/{res['logit_err_opposed']:.2f}")
