"""e338: the geometry of the fibres. From 1024 exact atom coordinates and logit effects: (1) the functional diameter
of physical balls (for each atom, the spread of the coordinates of its 10 physically nearest atoms) against the
physical diameter of functional balls (the spread of the write directions of its 10 functionally nearest atoms),
both relative to random 10-sets; (2) the local fibre dimension: participation rank of the write directions of the
20 functionally nearest atoms, against random 20-sets and against the 20 physically nearest; (3) near-physical /
far-functional and far-physical / near-functional pair counts against a shuffled null."""
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from quot_common import *
tag = sys.argv[1]; S = Setup(tag, levels=[0]); L = S.L; S = Setup(tag, levels=[L]); d = 16; nat = S.natural(); F = nat["F"][L]; tr, te = S.halves(len(S.idx)); Fc = F - F[tr].mean(0, keepdim=True); Z, Bv = logit_scores(nat["dl"], tr); P = pls(Fc[tr], Z[tr], d)
torch.manual_seed(0); atoms = torch.randperm(S.DFF, device=DEV)[:1024]; V = S.W2[atoms]; img = torch.zeros(1024, S.D, device=DEV); Fl = torch.zeros(1024, Bv.shape[1], device=DEV); cnt = torch.zeros(1024, device=DEV)
for p in range(6):
    r = S.inject_family(V, S.b + 1, seed=p); img.index_add_(0, r["a"], r["F"][L]); Fl.index_add_(0, r["a"], r["dl"] @ Bv); cnt.index_add_(0, r["a"], torch.ones(len(r["a"]), device=DEV))
img = img / cnt[:, None].clamp_min(1); Fl = unit(Fl / cnt[:, None].clamp_min(1)); z = unit(img @ P); Dp = 1 - V @ V.T; Dz = 1 - z @ z.T; Df = 1 - Fl @ Fl.T
for M in (Dp, Dz, Df): M.fill_diagonal_(float("inf"))
nnp = Dp.topk(20, dim=1, largest=False).indices; nnz = Dz.topk(20, dim=1, largest=False).indices; nnf = Df.topk(20, dim=1, largest=False).indices; rnd = torch.randint(0, 1024, (1024, 20), device=DEV)
spread = lambda X, nn: (1 - (unit(X[nn[:, :10]]).mean(1).norm(dim=1))).median().item(); fdim = lambda X, nn: float(torch.tensor([prank(X[nn[i]]) for i in range(0, 1024, 16)]).median())
res = dict(functional_diameter_of_physical_balls=spread(z, nnp), functional_diameter_random=spread(z, rnd), physical_diameter_of_functional_balls=spread(V, nnz), physical_diameter_random=spread(V, rnd), physical_diameter_of_effect_balls=spread(V, nnf), fibre_dim_functional_neighbours=fdim(V, nnz), fibre_dim_effect_neighbours=fdim(V, nnf), fibre_dim_physical_neighbours=fdim(V, nnp), fibre_dim_random=fdim(V, rnd), coordinate_dim_physical_neighbours=fdim(z, nnp), coordinate_dim_random=fdim(z, rnd))
iu = torch.triu_indices(1024, 1024, 1, device=DEV); dp, dz = Dp[iu[0], iu[1]], Dz[iu[0], iu[1]]; nearp, farp = dp <= dp.quantile(0.05), dp >= dp.quantile(0.5); nearz, farz = dz <= dz.quantile(0.05), dz >= dz.quantile(0.5); res.update(near_physical_far_functional=(nearp & farz).float().sum().item() / nearp.float().sum().item(), far_physical_near_functional=(farp & nearz).float().sum().item() / nearz.float().sum().item(), spearman_physical_functional=spearman(dp[::50], dz[::50]))
log(f"{tag} (1024 atoms): functional diameter of physical 10-balls {res['functional_diameter_of_physical_balls']:.2f} vs random 10-sets {res['functional_diameter_random']:.2f}; physical diameter of functional 10-balls {res['physical_diameter_of_functional_balls']:.2f} (effect balls {res['physical_diameter_of_effect_balls']:.2f}) vs random {res['physical_diameter_random']:.2f} | fibre dimension (participation rank of the writes of 20 functional neighbours) {res['fibre_dim_functional_neighbours']:.1f}, effect neighbours {res['fibre_dim_effect_neighbours']:.1f}, physical neighbours {res['fibre_dim_physical_neighbours']:.1f}, random {res['fibre_dim_random']:.1f}; coordinate dimension of physical neighbours {res['coordinate_dim_physical_neighbours']:.1f} vs random {res['coordinate_dim_random']:.1f} | of the physically closest 5% of pairs, {res['near_physical_far_functional']:.2f} are functionally far; of the functionally closest 5%, {res['far_physical_near_functional']:.2f} are physically far (baseline 0.50); Spearman(physical, functional distance) {res['spearman_physical_functional']:.2f}")
record(f"e338_fibres_{tag}", dict(model=tag, L=L, **res), f"fdiam phys-balls {res['functional_diameter_of_physical_balls']:.2f}/{res['functional_diameter_random']:.2f}; pdiam func-balls {res['physical_diameter_of_functional_balls']:.2f}/{res['physical_diameter_random']:.2f}; fibre dim {res['fibre_dim_functional_neighbours']:.1f} vs random {res['fibre_dim_random']:.1f}; near-phys-far-func {res['near_physical_far_functional']:.2f} far-phys-near-func {res['far_physical_near_functional']:.2f}")
