"""e349: the quotient across training (Pythia-410m revisions, block-2 writers, level 12, no training performed):
quotient dimension for 90% of the function score, own and random-16 scores, the overlap of the revision's quotient
with the final model's quotient (transported into the same coordinates by the identity, since the residual basis is
shared across checkpoints of one run), cross-family convergence (WDD vs random function-quotient overlap at the last
level), the off-manifold funnel (function dimension for perturbations orthogonal to the natural manifold), and the
linearity onset (self-consistency of a random family's images at 4x vs 1x)."""
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from quot_common import *
rev = sys.argv[1]; S = Setup("pythia410", levels=[0], revision=None if rev == "final" else rev); L = S.L; NB = S.NB; S = Setup("pythia410", levels=[S.b, L, NB - 2], revision=None if rev == "final" else rev); d = 16; nat = S.natural(); F = nat["F"][L]; tr, te = S.halves(len(S.idx)); Fc = F - F[tr].mean(0, keepdim=True); Z, _ = logit_scores(nat["dl"], tr); dln = unit(nat["dl"]); Q = pls(Fc[tr], Z[tr], 64); curve = {q: knn_cos(Fc @ Q[:, :q], dln, tr, te) for q in (1, 2, 4, 8, 16, 32, 64)}; torch.manual_seed(0)
res = dict(revision=rev, K=S.K, function_dim=next((q for q in curve if curve[q] >= 0.9 * curve[64]), 64), own16=curve[16], random16=knn_cos(Fc @ torch.linalg.qr(torch.randn(S.D, d, device=DEV))[0], dln, tr, te), identity16=accuracy((Fc @ Q[:, :d])[te], centroids((Fc @ Q[:, :d])[tr], S.lab_i[tr], S.K), S.lab_i[te]))
torch.save(Q[:, :d].cpu(), f"/workspace/wdd/results/e349_quotient_{rev}.pt")
Kf = 30; Sc = S.S0[S.b][S.typ] - S.S0[S.b][S.typ].mean(0, keepdim=True); Unat = torch.linalg.svd(Sc, full_matrices=False)[2][:64]; fams = {"wdd": S.W2[torch.randperm(S.DFF, device=DEV)[:Kf]], "random": unit(torch.randn(Kf, S.D, device=DEV)), "orthogonal": unit(torch.randn(Kf, S.D, device=DEV) - (torch.randn(Kf, S.D, device=DEV) @ Unat.T) @ Unat)}; fq = {}
for nm, V in fams.items():
    for lv in (L, NB - 2):
        r = S.inject_family(V, S.b + 1, seed=1); Fi = r["F"][lv]; a = r["a"]; tr2, te2 = S.halves(len(r["pos"]), seed=2); Fic = Fi - Fi[tr2].mean(0, keepdim=True); Zi, _ = logit_scores(r["dl"], tr2); Qi = pls(Fic[tr2], Zi[tr2], 64); cv = {q: knn_cos(Fic @ Qi[:, :q], unit(r["dl"]), tr2, te2) for q in (1, 2, 4, 8, 16, 32, 64)}; fq[(nm, lv)] = dict(Q=Qi[:, :d], dim=next((q for q in cv if cv[q] >= 0.9 * cv[64]), 64), own=cv[16])
r1 = S.inject_family(fams["random"], S.b + 1, seed=3); r4 = S.inject_family(fams["random"], S.b + 1, amp=4 * S.s_inj, seed=3); c1 = torch.stack([r1["F"][L][r1["a"] == k].mean(0) for k in range(Kf)]); c4 = torch.stack([r4["F"][L][r4["a"] == k].mean(0) for k in range(Kf)]); res.update(cross_family_overlap_mid=inside(fq[("wdd", L)]["Q"], fq[("random", L)]["Q"]), cross_family_overlap_last=inside(fq[("wdd", NB - 2)]["Q"], fq[("random", NB - 2)]["Q"]), orthogonal_function_dim=fq[("orthogonal", L)]["dim"], orthogonal_own=fq[("orthogonal", L)]["own"], random_function_dim=fq[("random", L)]["dim"], linearity_4x=((unit(c1) * unit(c4)).sum(1)).median().item(), chance=d / S.D)
log(f"{rev} (K {S.K}): function dim {res['function_dim']}, own-16 {res['own16']:.2f} vs random-16 {res['random16']:.2f}, identity-16 {res['identity16']:.2f} | cross-family (WDD vs random) quotient overlap at mid {res['cross_family_overlap_mid']:.2f}, at the last level {res['cross_family_overlap_last']:.2f} (chance {res['chance']:.3f}) | off-manifold family: function dim {res['orthogonal_function_dim']} (own {res['orthogonal_own']:.2f}) vs random family {res['random_function_dim']} | linearity of a random family's images at 4x vs 1x {res['linearity_4x']:.2f}")
record(f"e349_ckptquot_{rev}", res, f"dim {res['function_dim']} own {res['own16']:.2f} rnd {res['random16']:.2f} id {res['identity16']:.2f} | cross mid {res['cross_family_overlap_mid']:.2f} last {res['cross_family_overlap_last']:.2f} | orth dim {res['orthogonal_function_dim']} | lin4x {res['linearity_4x']:.2f}")
