"""e357: positive control on a known circuit, induction. Repeated random-token sequences; metric = per-token loss on
the second copy. Heads are mean-ablated one at a time; the 16 with the largest loss increase and 16 random others get
the full pairwise interaction matrix (|E_ij - E_i - E_j| relative to the singles, and its signed scalar version:
negative = sub-additive, as for components in series; positive = super-additive, as for redundant backups), spectral
clustering of the top-16 block, agreement of the clusters with attention-pattern labels (previous-token and
induction scores from eager attention) by adjusted Rand index, and joint-ablation non-additivity of the top-8 against
random 8-sets. The same statistics are then computed (i) for the same task-selected heads on natural text, the
blind-spot test for population averages, (ii) for heads selected on natural text, and (iii) for MLP neurons ranked by
attribution, on the induction data and on natural text. The old negatives (no units, additive, uniform interactions)
are credible only if these statistics detect the induction circuit where it is known to exist."""
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pc_common import *
tag = sys.argv[1]; c = Cache(tag); model, tok, fam = load_eager(c.name); arch = Arch(model, fam); NB, NH = arch.NB, arch.NH; torch.manual_seed(0); rng = random.Random(0)
KT = int(os.environ.get("WDD_KTOP", "12")); ind, off, half = induction_batch(tok, c, n=int(os.environ.get("WDD_NIND", "12")), half=128, seed=0); nat = c.s["eval_ids"][:int(os.environ.get("WDD_NNAT", "4"))].to(DEV)
m_ind = lambda lg: induction_loss(lg, ind, off, half); m_nat = lambda lg: token_loss(lg, nat)
MAi, MMi, lgi = capture_means(model, arch, ind); MAn, MMn, lgn = capture_means(model, arch, nat); bi = m_ind(lgi); bn = m_nat(lgn); first = induction_loss(lgi, ind, off, half, second=False).mean().item(); del lgi, lgn
pref, prev = attention_scores(model, ind, off, half, NB, NH); heads = [(l, h) for l in range(NB) for h in range(NH)]
def singles(ids, metric, base, comps, kind, MA, MM): return {x: metric(ablate(model, arch, ids, heads=[x] if kind == "head" else (), neurons=[x] if kind == "neuron" else (), MA=MA, MM=MM)) - base for x in comps}
def label(x): l, h = x; p, q = pref[l, h].item(), prev[l, h].item(); return "induction" if p >= 0.2 and p >= q else ("previous" if q >= 0.3 else "other")
def analyse(ids, metric, base, U, kind, MA, MM, E1, labels=None):
    I, Sg = pairwise(model, arch, ids, metric, base, U, kind, MA, MM, E1); st = block_stats(I, Sg, KT); cl, k, ev = spectral(I[:KT, :KT].abs()); st.update(clusters=cl, k=k, ari=ari(cl, labels[:KT]) if labels else None, ktop=KT)
    return st, I
out = {}
E1h = singles(ind, m_ind, bi, heads, "head", MAi, MMi); eff = torch.tensor([E1h[x].mean().item() for x in heads]); order = eff.argsort(descending=True).tolist(); top = [heads[i] for i in order[:KT]]; rest = [heads[i] for i in order[KT:]]; U = top + rng.sample(rest, KT); labs = [label(x) for x in U]
st, I = analyse(ind, m_ind, bi, U, "head", MAi, MMi, E1h, labs); na_top = set_nonadditivity(model, arch, ind, m_ind, bi, top[:8], "head", MAi, MMi, E1h); na_r = [set_nonadditivity(model, arch, ind, m_ind, bi, rng.sample(rest, 8), "head", MAi, MMi, E1h) for _ in range(4)]
out["heads_on_induction"] = dict(stats=st, top=top, labels_top=labs[:KT], top_effects=[E1h[x].mean().item() for x in top], na_top8=na_top, na_random8=na_r, n_induction_label_all=int(sum(label(x) == "induction" for x in heads)), n_previous_label_all=int(sum(label(x) == "previous" for x in heads)))
E1hn = singles(nat, m_nat, bn, heads, "head", MAn, MMn); st2, I2 = analyse(nat, m_nat, bn, U, "head", MAn, MMn, E1hn, labs); na_top_n = set_nonadditivity(model, arch, nat, m_nat, bn, top[:8], "head", MAn, MMn, E1hn)
out["same_heads_on_natural"] = dict(stats=st2, na_top8=na_top_n, top_effects_natural=[E1hn[x].mean().item() for x in top])
effn = torch.tensor([E1hn[x].mean().item() for x in heads]); ordn = effn.argsort(descending=True).tolist(); topn = [heads[i] for i in ordn[:KT]]; restn = [heads[i] for i in ordn[KT:]]; Un = topn + rng.sample(restn, KT)
st3, _ = analyse(nat, m_nat, bn, Un, "head", MAn, MMn, E1hn, [label(x) for x in Un]); out["natural_selected_heads"] = dict(stats=st3, top=topn, labels_top=[label(x) for x in topn], na_top8=set_nonadditivity(model, arch, nat, m_nat, bn, topn[:8], "head", MAn, MMn, E1hn), na_random8=[set_nonadditivity(model, arch, nat, m_nat, bn, rng.sample(restn, 8), "head", MAn, MMn, E1hn) for _ in range(4)], overlap_with_induction_top16=len(set(topn) & set(top)) / KT)
for dname, ids, metric, base, MA, MM in (("induction", ind, m_ind, bi, MAi, MMi), ("natural", nat, m_nat, bn, MAn, MMn)):
    sc = neuron_attr(model, arch, ids, metric, MM); DFF = sc[0].numel(); allsc = torch.cat([sc[l] for l in range(NB)]); o = allsc.argsort(descending=True)[:KT].tolist(); topN = [(i // DFF, i % DFF) for i in o]; randN = []
    while len(randN) < KT:
        x = (rng.randrange(NB), rng.randrange(DFF))
        if x not in topN and x not in randN: randN.append(x)
    UN = topN + randN; E1n = singles(ids, metric, base, UN, "neuron", MA, MM); stn, _ = analyse(ids, metric, base, UN, "neuron", MA, MM, E1n)
    out[f"neurons_on_{dname}"] = dict(stats=stn, top=topN, top_effects=[E1n[x].mean().item() for x in topN], random_effects=[E1n[x].mean().item() for x in randN], na_top8=set_nonadditivity(model, arch, ids, metric, base, topN[:8], "neuron", MA, MM, E1n), na_random8=set_nonadditivity(model, arch, ids, metric, base, randN[:8], "neuron", MA, MM, E1n), attribution_vs_exact_spearman=float(torch.corrcoef(torch.stack([torch.tensor([allsc[l * DFF + i].item() for (l, i) in UN]).argsort().argsort().float(), torch.tensor([E1n[x].mean().item() for x in UN]).argsort().argsort().float()]))[0, 1]))
nr = lambda d: sum(x["nonadditivity"] for x in d) / len(d)
h, hn, hs = out["heads_on_induction"], out["same_heads_on_natural"], out["natural_selected_heads"]
log(f"{tag}: induction works: loss first copy {first:.2f} vs second copy {bi.mean().item():.2f}; heads labelled induction {h['n_induction_label_all']}, previous-token {h['n_previous_label_all']} of {NB * NH}; top-16 labels {dict((x, h['labels_top'].count(x)) for x in set(h['labels_top']))} | HEADS ON INDUCTION: interaction top {h['stats']['I_top']:.2f} vs random {h['stats']['I_random']:.2f} vs cross {h['stats']['I_cross']:.2f}; signed top {h['stats']['signed_top']:+.2f} (sub-additive {h['stats']['subadditive_fraction_top']:.2f}, super-additive {h['stats']['superadditive_fraction_top']:.2f}); clusters k {h['stats']['k']}, ARI with attention labels {h['stats']['ari']:.2f}; set non-additivity top-8 {h['na_top8']['nonadditivity']:.2f} (joint/sum {h['na_top8']['joint_over_sum']:.2f}) vs random-8 {nr(h['na_random8']):.2f} | SAME HEADS ON NATURAL TEXT: interaction top {hn['stats']['I_top']:.2f} vs random {hn['stats']['I_random']:.2f}; ARI {hn['stats']['ari']:.2f}; non-additivity top-8 {hn['na_top8']['nonadditivity']:.2f} | NATURAL-SELECTED HEADS: interaction top {hs['stats']['I_top']:.2f} vs random {hs['stats']['I_random']:.2f}; non-additivity {hs['na_top8']['nonadditivity']:.2f} vs {nr(hs['na_random8']):.2f}; overlap with induction top-16 {hs['overlap_with_induction_top16']:.2f} | NEURONS: induction interaction top {out['neurons_on_induction']['stats']['I_top']:.2f} vs random {out['neurons_on_induction']['stats']['I_random']:.2f}, non-additivity {out['neurons_on_induction']['na_top8']['nonadditivity']:.2f} vs {out['neurons_on_induction']['na_random8']['nonadditivity']:.2f}; natural interaction top {out['neurons_on_natural']['stats']['I_top']:.2f} vs random {out['neurons_on_natural']['stats']['I_random']:.2f}, non-additivity {out['neurons_on_natural']['na_top8']['nonadditivity']:.2f} vs {out['neurons_on_natural']['na_random8']['nonadditivity']:.2f}")
record(f"e357_indctrl_{tag}", dict(model=tag, first_copy_loss=first, second_copy_loss=bi.mean().item(), **{k: {kk: (vv if not isinstance(vv, list) or not vv or not isinstance(vv[0], tuple) else [list(t) for t in vv]) for kk, vv in v.items()} for k, v in out.items()}), f"heads-on-induction I top/random {h['stats']['I_top']:.2f}/{h['stats']['I_random']:.2f} signed {h['stats']['signed_top']:+.2f} ARI {h['stats']['ari']:.2f} NA {h['na_top8']['nonadditivity']:.2f}/{nr(h['na_random8']):.2f} | same-heads-on-natural I {hn['stats']['I_top']:.2f}/{hn['stats']['I_random']:.2f} ARI {hn['stats']['ari']:.2f} | natural-selected I {hs['stats']['I_top']:.2f}/{hs['stats']['I_random']:.2f} | neurons ind I {out['neurons_on_induction']['stats']['I_top']:.2f}/{out['neurons_on_induction']['stats']['I_random']:.2f} nat I {out['neurons_on_natural']['stats']['I_top']:.2f}/{out['neurons_on_natural']['stats']['I_random']:.2f}")
